name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:14-alpine
    steps:
      - name: Log node node-version
        run: |
          node -v
          uname -r
          cat /etc/os-release