name: matrix
on: push

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [6,8,10]
        include:
          - os: ubuntu-latest
            node-version: 8
            is_ubuntu_8: "true"
        exclude:
          - os: ubuntu-latest
            node-version: 6
          - os: macos-latest
            node-version: 8
    env:
      IS_UBUNTU_8: $ {{ matrix.is_ubuntu_8 }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Log node node-version
        run: |
          node -v
          echo ${IS_UBUNTU_8}
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Log node node-version again
        run: node -v